# aiff-to-wav
TOOL = aiff-to-wav
SCRIPTS = aiff-to-wav.sh find-aiff-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-aiff-dirs.sh
WORKDIR_GLOB = .aiff2wav.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
