# flac-to-vorbis
TOOL = flac-to-vorbis
SCRIPTS = flac-to-vorbis.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2vorbis.*
DELETE_TARGET = delete-sources
HELP_EXTRA =   Quality: make convert ARGS='-Q q6'
include ../../lib/tool.mk
