# aiff-to-flac
TOOL = aiff-to-flac
SCRIPTS = aiff-to-flac.sh find-aiff-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-aiff-dirs.sh
WORKDIR_GLOB = .aiff2flac.*
DELETE_TARGET = delete-aiffs
HAS_CONVERT_VERBOSE = 1
HAS_CONVERT_CLEAN = 1
HAS_RETAG = 1
HELP_EXTRA =   Extra: convert-clean / retag
include ../../lib/tool.mk
