TOOL = flac-dupes
SCRIPTS = flac-dupes.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flacdupes.*
HAS_CONVERT_VERBOSE = 1
HELP_EXTRA =   Fingerprint: make convert ARGS='--fingerprint'
include ../../lib/tool.mk
