TOOL = audio-artwork
SCRIPTS = audio-artwork.sh find-audio-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-audio-dirs.sh
WORKDIR_GLOB = .audioart.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
