# dsf-to-flac
TOOL = dsf-to-flac
SCRIPTS = dsf-to-flac.sh find-dsd-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-dsd-dirs.sh
WORKDIR_GLOB = .dsf2flac.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
