# wv-to-flac
TOOL = wv-to-flac
SCRIPTS = wv-to-flac.sh find-wv-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-wv-dirs.sh
WORKDIR_GLOB = .wv2flac.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
