# flac-to-wma
TOOL = flac-to-wma
SCRIPTS = flac-to-wma.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2wma.*
DELETE_TARGET = delete-sources
HELP_EXTRA =   Quality: make convert ARGS='-Q 192'
include ../../lib/tool.mk
