# flac-to-wv
TOOL = flac-to-wv
SCRIPTS = flac-to-wv.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2wv.*
DELETE_TARGET = delete-sources
include ../lib/tool.mk
