TOOL = disc-inventory
SCRIPTS = disc-inventory.sh find-disc-units.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-disc-units.sh
WORKDIR_GLOB = .discinv.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
