# ape-to-flac
TOOL = ape-to-flac
SCRIPTS = ape-to-flac.sh find-ape-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-ape-dirs.sh
WORKDIR_GLOB = .ape2flac.*
DELETE_TARGET = delete-sources
include ../lib/tool.mk
