# wav-to-aiff
TOOL = wav-to-aiff
SCRIPTS = wav-to-aiff.sh find-wav-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-wav-dirs.sh
WORKDIR_GLOB = .wav2aiff.*
DELETE_TARGET = delete-sources
include ../lib/tool.mk
