# bluray-to-flac
TOOL = bluray-to-flac
SCRIPTS = bluray-to-flac.sh find-bdmv-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-bdmv-dirs.sh
WORKDIR_GLOB = .bluray2flac.*
DELETE_TARGET = delete-sources
HELP_EXTRA =   Note: BDMV / decrypted media only
include ../../lib/tool.mk
