# flac-to-alac
TOOL = flac-to-alac
SCRIPTS = flac-to-alac.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2alac.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
