TOOL = flac-cue-export
SCRIPTS = flac-cue-export.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flaccue.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
