# flac-to-caf
TOOL = flac-to-caf
SCRIPTS = flac-to-caf.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2caf.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
