TOOL = flac-authenticity
SCRIPTS = flac-authenticity.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flacauth.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
