TOOL = playlist-normalize
SCRIPTS = playlist-normalize.sh find-playlist-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-playlist-dirs.sh
WORKDIR_GLOB = .plnorm.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
