TOOL = silence-detect
SCRIPTS = silence-detect.sh find-audio-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-audio-dirs.sh
WORKDIR_GLOB = .silencedet.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
