TOOL = library-prune
SCRIPTS = library-prune.sh find-portable-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-portable-dirs.sh
WORKDIR_GLOB = .libprune.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
