TOOL = playlist-export
SCRIPTS = playlist-export.sh find-playlist-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-playlist-dirs.sh
WORKDIR_GLOB = .plexp.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
