TOOL = flac-artwork
SCRIPTS = flac-artwork.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flacart.*
HAS_CONVERT_VERBOSE = 1
HELP_EXTRA =   Extract: make convert ARGS='-x' | Force: ARGS='-y'
include ../../lib/tool.mk
