TOOL = flac-inventory
SCRIPTS = flac-inventory.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flacinv.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
