TOOL = perms-normalize
SCRIPTS = perms-normalize.sh find-audio-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-audio-dirs.sh
WORKDIR_GLOB = .permnorm.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
