# flac-to-ape
TOOL = flac-to-ape
SCRIPTS = flac-to-ape.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2ape.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
