TOOL = flac-optimize
SCRIPTS = flac-optimize.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flacopt.*
HAS_CONVERT_VERBOSE = 1
HELP_EXTRA =   Level: make convert ARGS='-c 5'
include ../../lib/tool.mk
