# flac-to-wav
TOOL = flac-to-wav
SCRIPTS = flac-to-wav.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2wav.*
DELETE_TARGET = delete-flacs
HAS_CONVERT_VERBOSE = 1
HELP_EXTRA =   Extra: convert-verbose
include ../../lib/tool.mk
