TOOL = audio-replaygain
SCRIPTS = audio-replaygain.sh find-audio-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-audio-dirs.sh
WORKDIR_GLOB = .audiorg.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
