# flac-to-tta
TOOL = flac-to-tta
SCRIPTS = flac-to-tta.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2tta.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
