TOOL = playlist-audit
SCRIPTS = playlist-audit.sh find-playlist-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-playlist-dirs.sh
WORKDIR_GLOB = .plaudit.*
HAS_CONVERT_VERBOSE = 1
include ../../lib/tool.mk
