# flac-to-mpc
TOOL = flac-to-mpc
SCRIPTS = flac-to-mpc.sh find-flac-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-flac-dirs.sh
WORKDIR_GLOB = .flac2mpc.*
DELETE_TARGET = delete-sources
HELP_EXTRA =   Quality: make convert ARGS='-Q standard'
include ../../lib/tool.mk
