# streams-to-flac
TOOL = streams-to-flac
SCRIPTS = streams-to-flac.sh find-media-dirs.sh convert-all.sh lib/*.sh
FIND_SCRIPT = find-media-dirs.sh
WORKDIR_GLOB = .streams2flac.*
DELETE_TARGET = delete-sources
include ../../lib/tool.mk
